language: python
python:
  - "3.5"
install:
  - pip install numpy
  - pip install sympy
  - pip install coveralls
  - pip install pytest-cov
  - pip install matplotlib
script:
  - pytest --cov SSplines/
after_success:
  - coveralls
